version: '3'
services:
  db:
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: 'common'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql_volume:/var/lib/mysql

  nginx:
    image: nginx:1.15.6
    ports:
      - '8000:80'
    depends_on: # 追加
      - app
      - db
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  app:
    build: ./php
    volumes:
      - .:/var/www/html
    depends_on:
      - db
